### ISSUE TITLE
 Atenção!  Os dados enviados pela loja apresentaram os seguintes problemas

### ISSUE THREAD

**Issue by mageuser** [rafaelpatro/Quack-BB#10]
Desculpa ficar incomodando, devo criar novas issues ou continuar em uma só?
Mensagem informada pelo banco na hora de gerar o boleto, qual é o arquivo que está passando essas variáveis para o bb?

Atenção!

Os dados enviados pela loja apresentaram os seguintes problemas:

Informe o nome do pagador. (C008-000)

**Comment by rafaelpatro** [comment]
Como está preenchendo o formulário? Pode dar um print?
Quando identifica CPF, o módulo usa o campo Nome (firstname + lastname); quando CNPJ, o campo Empresa (company).

**Comment by mageuser** [comment]
Estou utilizando o https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro, se não me engano o CPF/CNPJ é o campo taxvat e o nome firstname + lastname, o campo empresa seria o nome também...
Já envio prints

**Comment by mageuser** [comment]
Outra coisa, depois dessa atualização o magento fica reportando erro de cache:
Um ou mais tipos de cache são inválidos: Blocks HTML output. Clique aqui para ir a página de Gerenciamento de Cache e atualizar todo cache.

**Comment by mageuser** [comment]
Mesmo atualizando, em alguns segundos ele diz que já está invalidado...

**Comment by mageuser** [comment]
O company está habilitado em ambos os casos, seria a empresa que o cliente trabalha, talvez eu desabilite esta opção...

O firstname e o lastname, quando seleciona o tipo pessoa, no caso, juridica, os campos nome e sobrenome se alteram para Razão Social e Nome Fantasia.

![fisica](https://cloud.githubusercontent.com/assets/27354497/24990328/8c951f04-1fe9-11e7-8b17-4ff2bf246491.PNG)
![juridica](https://cloud.githubusercontent.com/assets/27354497/24990329/8c9863da-1fe9-11e7-87b6-65e7f9c8a432.PNG)

**Comment by mageuser** [comment]
> Outra coisa, depois dessa atualização o magento fica reportando erro de cache:
Um ou mais tipos de cache são inválidos: Blocks HTML output. Clique aqui para ir a página de Gerenciamento de Cache e atualizar todo cache.

Peço desculpas pela informação errada, é por que nosso sistema está sincronizado com o site, atualizando preço e estoque dos produtos...

**Comment by rafaelpatro** [comment]
Pode realizar um teste utilizando CPF, Nome, Sobrenome? O CPF precisa ser válido, e o CEP também. Aguardo o resultado.

Acho que vou colocar uma opção para o uso dos campos Razão Social, Nome, CPF, CNPJ. Cada loja tem sua personalização.

**Comment by mageuser** [comment]
@rafaelpatro  	

Atenção!

Os dados enviados pela loja apresentaram os seguintes problemas:

    CPF/CNPJ não informado para cobrança registrada (C031-000)

EDITADO:

Esse erro acontece quando a opção Permitir Checkout para Visitantes->Sim

**Comment by mageuser** [comment]
Ele passou pela validação do nome? Pois nesse caso deu erro de cpf/cpnj.

EDITADO:

Esse erro acontece quando a opção Permitir Checkout para Visitantes->Sim

**Comment by kauanguesser** [comment]
Quando o usuário se cadastra pela página do one step checkout para realizar o pagamento, e o pagamento falha, a conta dele não é cadastrada, não sei se quando o pagamento der certo o usuário vai ser registrado na loja...pois ainda não consegui avançar esse passo...

**Comment by kauanguesser** [comment]
Chega a ser registrado o pedido, porem com cliente vazio:

![clientevazio](https://cloud.githubusercontent.com/assets/27354497/25004541/3d2c603e-202b-11e7-9a6a-edaa4f0cdcda.JPG)

**Comment by mageuser** [comment]
Agora realizei o teste com uma conta já previamente cadastrada:
 	

Atenção!

Os dados enviados pela loja apresentaram os seguintes problemas:

    Informe o nome do pagador. (C008-000)

**Comment by mageuser** [comment]
O erro persiste, tanto para novos cadastros quanto para antigos:
Atenção!

Os dados enviados pela loja apresentaram os seguintes problemas:

Informe o nome do pagador. (C008-000)

**Comment by rafaelpatro** [comment]
Coloquei um log para visualizar os campos da requisição.
Preciso que mantenha o Log ativo, e informe o que aparecer em `var/log/system.log`, ao clicar em Finalizar Pedido.
Ou pode me enviar o arquivo inteiro se preferir.
Fico aguardando o próximo teste.

**Comment by mageuser** [comment]
Informe o nome do pagador. (C008-000)

Continua dando esse erro, o arquivo system.log não foi gerado...

**Comment by rafaelpatro** [comment]
Sim, o Log precisa ser ativado em _Sistema > Configurações > Desenvolvedor_
![image](https://cloud.githubusercontent.com/assets/13813964/25007318/6bc60322-2036-11e7-94fa-47fd31f65a20.png)

**Comment by rafaelpatro** [comment]
Enviei mais uma correção. Pode testar novamente.

**Comment by rafaelpatro** [comment]
Pode testar novamente. Neste caso não é necessário fazer um novo pedido. Não fará diferença. Basta clicar sobre o link de pagamento de um pedido já realizado.
Aguardo retorno.

**Comment by mageuser** [comment]
Um momento já posto o log...

**Comment by kauanguesser** [comment]
Deu certo muito obrigado
[document.pdf](https://github.com/rafaelpatro/Quack_BB/files/920071/document.pdf)

**Comment by rafaelpatro** [comment]
Reparei que deu um probleminha com os acentos. São José ficou SO JOS. Mais
tarde eu arrumo isso.

**Comment by mageuser** [comment]
Sim, também percebi, posso usar o utf8_encode() ou é melhor remover os acentos? SAO JOSE, em vez de SÃO JOSÉ?

**Comment by mageuser** [comment]
O senhor deseja os logs também?

**Comment by rafaelpatro** [comment]
Utf8 não vai resolver. Mais tarde eu conserto. Não preciso mais dos logs
