### ISSUE TITLE
Pagamento via Boleto

### ISSUE THREAD

**Issue by mageuser** [rafaelpatro/Quack-BB#12]
Olá, estou aqui novamente para reportar alguns erros.

Quando o cliente vai na página do seu pedido para ver mais informações aparece o seguinte:

Forma de Pagamento
Banco do Brasil
Método:
Débito Online

No caso o método foi boleto, e está aparecendo débito online.

Se o cliente clicar em:
Pagar Online no Banco do Brasil
 Se já realizou o pagamento, aguarde a compensação. Você receberá uma confirmação em breve.

O bb informa:

Atenção!

Os dados enviados pela loja apresentaram os seguintes problemas:

O Numero do Titulo informado nao esta disponivel. (C008-000)
Enviar

Ficarei muito grato se você puder ajudar, se eu não me engano, em algum branch não estava assim, ele detectava que era boleto e falava para tirar a 2° via, posso estar enganado rs.

Obrigado desde já! E Feliz páscoa para você e sua família!!

**Comment by mageuser** [comment]
@rafaelpatro  Segui as configurações, sabe o que pode ser?

**Comment by rafaelpatro** [comment]
Refatorei alguns métodos recentemente. É possível que eu tenha estragado algo.

**Comment by rafaelpatro** [comment]
Testa esse release, anterior à refatoração da classe Helper
https://github.com/rafaelpatro/Quack_BB/tree/73e60e6ecca4129e919ed663b544379f59b01baa

**Comment by rafaelpatro** [comment]
Consegue testar este branch? Acredito que esteja Ok agora.
https://github.com/rafaelpatro/Quack_BB/tree/bugfix_bank_slip
Aguardo teu retorno.

**Comment by mageuser** [comment]
@rafaelpatro Olá, desculpa a demora... Agora o módulo sumiu das formas de pagamento.
![formas](https://cloud.githubusercontent.com/assets/27354497/25099270/f26a8be8-2381-11e7-824e-7fe731309896.JPG)

**Comment by mageuser** [comment]
2017-04-17T18:25:30+00:00 ERR (3): Warning: simplexml_load_string(): Entity: line 176: parser error : Entity 'lsaquo' not defined  in /home/meudiretorio/public_html/lib/Varien/Simplexml/Config.php on line 510
2017-04-17T18:25:30+00:00 ERR (3): Warning: simplexml_load_string():  de cobrança. Tags HTML não são permitidas, exceto a quebra de linha &amp;lsaquo;  in /home/meudiretorio/public_html/lib/Varien/Simplexml/Config.php on line 510
2017-04-17T18:25:30+00:00 ERR (3): Warning: simplexml_load_string():                                                                                ^  in /home/meudiretorio/public_html/lib/Varien/Simplexml/Config.php on line 510
2017-04-17T18:25:30+00:00 ERR (3): Warning: simplexml_load_string(): Entity: line 176: parser error : Entity 'lraquo' not defined  in /home/meudiretorio/public_html/lib/Varien/Simplexml/Config.php on line 510
2017-04-17T18:25:30+00:00 ERR (3): Warning: simplexml_load_string(): ça. Tags HTML não são permitidas, exceto a quebra de linha &amp;lsaquo;br&amp;lraquo;  in /home/meudiretorio/public_html/lib/Varien/Simplexml/Config.php on line 510
2017-04-17T18:25:30+00:00 ERR (3): Warning: simplexml_load_string():                                                                                ^  in /home/meudiretorio/public_html/lib/Varien/Simplexml/Config.php on line 510

**Comment by rafaelpatro** [comment]
Corrigido!
https://github.com/rafaelpatro/Quack_BB/tree/bugfix_bank_slip

**Comment by mageuser** [comment]
@rafaelpatro 
O Módulo agora mostra isto:

Forma de Pagamento

Banco do Brasil
Método:
Method
Situação:
Status

Na tela do pedido.

Está configurado para o cliente clicar no botão na tela de sucesso, estou com dúvidas em relação de como o banco do brasil informa para o site qual foi o método escolhido, não seria algum problema na url de retorno? Eu configurei conforme orientações suas em outra Issue.

Obrigado!

**Comment by mageuser** [comment]
![pagamento](https://cloud.githubusercontent.com/assets/27354497/25103153/d12ec0e2-2391-11e7-8b4d-0104f59b65b7.JPG)

**Comment by mageuser** [comment]
No boleto ainda persiste o erro de acentuação, ficando SO JOS-SC (em vez de são josé-sc)
E o nome do pagador está configurado para aparecer somente o primeiro nome?

Obrigado desde já.

**Comment by mageuser** [comment]
Quando clico em Pagar Online no Banco do Brasil (botão verde), ao selecionar boleto bancário a seguinte mensagem é exibida:
![bb](https://cloud.githubusercontent.com/assets/27354497/25103322/721bb744-2392-11e7-8aa3-a08b5a3d4b92.JPG)

**Comment by rafaelpatro** [comment]
Atualizou a cache de Translate também?
Chegou a emitir a 1a via para esse pedido?
Pode dar uma conferida no arquivo bb.log?

**Comment by mageuser** [comment]
@rafaelpatro Olá, bom dia, novamente peço desculpas pela demora.
1) Atualizei todos os caches.
2) Cheguei a emitir a 1a via.
3) LOG:

idConv=315557&refTran=29836920000000028&valorSonda=1773&formato=02&%00%2A%00_hasDataChanges=0&%00%2A%00_isDeleted=0
2017-04-18T11:10:05+00:00 DEBUG (7): 





<FORMULARIO>
<ENTRADA nome='reftran' valor=''/>
<ENTRADA nome='valor' valor=''/>
<ENTRADA nome='idConv' valor=''/>
<ENTRADA nome='tpPagamento' valor=''/>
<ENTRADA nome='situacao' valor=''/>
<ENTRADA nome='dataPagamento' valor=''/>
</FORMULARIO>

2017-04-18T11:10:05+00:00 DEBUG (7): Quack_BB_Model_Standard::capture() started
2017-04-18T11:10:05+00:00 DEBUG (7): Quack_BB_Model_Standard::sonda() started
2017-04-18T11:10:05+00:00 DEBUG (7): URI: POST /site/mpag/REC3.jsp HTTP/1.1
Host: mpag.bb.com.br
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Zend_Http_Client
Content-Type: application/x-www-form-urlencoded
Content-Length: 116

idConv=315557&refTran=29836920000000033&valorSonda=11262&formato=02&%00%2A%00_hasDataChanges=0&%00%2A%00_isDeleted=0
2017-04-18T11:10:05+00:00 DEBUG (7): 





<FORMULARIO>
<ENTRADA nome='reftran' valor=''/>
<ENTRADA nome='valor' valor=''/>
<ENTRADA nome='idConv' valor=''/>
<ENTRADA nome='tpPagamento' valor=''/>
<ENTRADA nome='situacao' valor=''/>
<ENTRADA nome='dataPagamento' valor=''/>
</FORMULARIO>

2017-04-18T11:10:05+00:00 DEBUG (7): Quack_BB_Model_Standard::capture() started
2017-04-18T11:10:05+00:00 DEBUG (7): Quack_BB_Model_Standard::sonda() started
2017-04-18T11:10:05+00:00 DEBUG (7): URI: POST /site/mpag/REC3.jsp HTTP/1.1
Host: mpag.bb.com.br
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Zend_Http_Client
Content-Type: application/x-www-form-urlencoded
Content-Length: 116

idConv=315557&refTran=29836920000000034&valorSonda=11262&formato=02&%00%2A%00_hasDataChanges=0&%00%2A%00_isDeleted=0
2017-04-18T11:10:05+00:00 DEBUG (7): 





<FORMULARIO>
<ENTRADA nome='reftran' valor=''/>
<ENTRADA nome='valor' valor=''/>
<ENTRADA nome='idConv' valor=''/>
<ENTRADA nome='tpPagamento' valor=''/>
<ENTRADA nome='situacao' valor=''/>
<ENTRADA nome='dataPagamento' valor=''/>
</FORMULARIO>

2017-04-18T11:10:05+00:00 DEBUG (7): Quack_BB_Model_Standard::capture() started
2017-04-18T11:10:05+00:00 DEBUG (7): Quack_BB_Model_Standard::sonda() started
2017-04-18T11:10:05+00:00 DEBUG (7): URI: POST /site/mpag/REC3.jsp HTTP/1.1
Host: mpag.bb.com.br
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Zend_Http_Client
Content-Type: application/x-www-form-urlencoded
Content-Length: 116

idConv=315557&refTran=29836920000000035&valorSonda=11262&formato=02&%00%2A%00_hasDataChanges=0&%00%2A%00_isDeleted=0
2017-04-18T11:10:05+00:00 DEBUG (7): 





<FORMULARIO>
<ENTRADA nome='reftran' valor=''/>
<ENTRADA nome='valor' valor=''/>
<ENTRADA nome='idConv' valor=''/>
<ENTRADA nome='tpPagamento' valor=''/>
<ENTRADA nome='situacao' valor=''/>
<ENTRADA nome='dataPagamento' valor=''/>
</FORMULARIO>

2017-04-18T11:10:06+00:00 DEBUG (7): Quack_BB_Model_Standard::capture() started
2017-04-18T11:10:06+00:00 DEBUG (7): Quack_BB_Model_Standard::sonda() started
2017-04-18T11:10:06+00:00 DEBUG (7): URI: POST /site/mpag/REC3.jsp HTTP/1.1
Host: mpag.bb.com.br
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Zend_Http_Client
Content-Type: application/x-www-form-urlencoded
Content-Length: 115

idConv=315557&refTran=29836920000000042&valorSonda=1773&formato=02&%00%2A%00_hasDataChanges=0&%00%2A%00_isDeleted=0
2017-04-18T11:10:06+00:00 DEBUG (7): 





<FORMULARIO>
<ENTRADA nome='reftran' valor=''/>
<ENTRADA nome='valor' valor=''/>
<ENTRADA nome='idConv' valor=''/>
<ENTRADA nome='tpPagamento' valor=''/>
<ENTRADA nome='situacao' valor=''/>
<ENTRADA nome='dataPagamento' valor=''/>
</FORMULARIO>

**Comment by rafaelpatro** [comment]
Bom dia @kauanguesser 
Se o log que enviou estiver completo, é possível que esteja com problemas de conexão.
A última linha de cada consulta deveria trazer o resultado em formato XML. Mas não aparece nada em seu log.
![image](https://cloud.githubusercontent.com/assets/13813964/25130004/e8e206e2-2416-11e7-9708-1dc8e4fb44ed.png)

Esse resultado é importante pois diz a loja quais foram as escolhas do usuário no ambiente do banco.

**Comment by rafaelpatro** [comment]
O log deveria estar parecido com isso:

2017-04-18T08:28:07+00:00 DEBUG (7): Quack_BB_Model_Standard::getRedirectFields() started
2017-04-18T08:30:01+00:00 DEBUG (7): Quack_BB_Model_Standard::capture() started
2017-04-18T08:30:01+00:00 DEBUG (7): Quack_BB_Model_Standard::sonda() started
2017-04-18T08:30:02+00:00 DEBUG (7): URI: POST /site/mpag/REC3.jsp HTTP/1.1
Host: mpag.bb.com.br
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Zend_Http_Client
Content-Type: application/x-www-form-urlencoded
Content-Length: 115

idConv=123456&refTran=76543210000064979&valorSonda=8990&formato=02&%00%2A%00_hasDataChanges=0&%00%2A%00_isDeleted=0
2017-04-18T08:30:02+00:00 DEBUG (7):
```xml
<FORMULARIO>
	<ENTRADA nome='reftran' valor='76543210000064979'/>
	<ENTRADA nome='valor' valor='8990'/>
	<ENTRADA nome='idConv' valor='123456'/>
	<ENTRADA nome='tpPagamento' valor='3'/>
	<ENTRADA nome='situacao' valor='00'/>
	<ENTRADA nome='dataPagamento' valor='18042017'/>
</FORMULARIO>
```

**Comment by mageuser** [comment]
Aqui está o log completo:
[bb.log](https://github.com/rafaelpatro/Quack_BB/files/929741/bb.txt)

O que pode ser? O que pode estar dificultando a conexão?

**Comment by mageuser** [comment]
![bb1](https://cloud.githubusercontent.com/assets/27354497/25132337/9f0ae454-241f-11e7-9c03-28ea66711b48.JPG)![bb2](https://cloud.githubusercontent.com/assets/27354497/25132336/9f09db04-241f-11e7-8108-1cc6c016608c.JPG)

**Comment by rafaelpatro** [comment]
@kauanguesser 
Verifiquei no `bb.log` que vc enviou. O problema é que o banco está retornando tudo vazio.

Não sei a razão disso. Terá que ver com o banco. Mas é provável que seja por vc ainda estar em fase de testes. Se for esse o caso, não poderá testar a 2a via, a menos que simule a resposta, com os valores que vc precisa.

![image](https://cloud.githubusercontent.com/assets/13813964/25140024/51293702-2435-11e7-8955-dd5bc4001b3d.png)

**Comment by mageuser** [comment]
Olá, continuo com o mesmo problema, o banco informou que não é por estar em fase de teste...

**Comment by FabioRLeite** [comment]
isso acontece por que o numero gerado é duplicado no banco, provavelmente alguem gerou um boleto com o sistema do proprio banco com o mesmo numero da loja vitual, resolvi meu problema colocando 11111 ao inves de 0000 depois do numero do convenio

**Comment by rafaelpatro** [comment]
Boa sugestão!
Negócio é usar 11112 e daí por diante agora.
Vlw Fabio

**Comment by alekissi** [comment]
Olá, estou criando uma página semelhante, mas o cliente não vai poder efetuar o pagamento, vai apenas emitir o boleto.
Quando tento emitir uma segunda via de boleto já registrado aparece a mensagem de erro "Titulo já incluído anteriormente. (C008-000)"
O form que estou enviando é esse:
`<form action="https://mpag.bb.com.br/site/mpag/" method="post" name="pagamento" >  `      
            `<input type="hidden" name="idConv" value="123456" />`
            `<input type="hidden" name="refTran" value="12345670000127517" />`
            `<input type="hidden" name="valor" value="20833" />`
            `<input type="hidden" name="qtdPontos" value="0" />`
            `<input type="hidden" name="dtVenc" value="10012019" />`
            `<input type="hidden" name="tpPagamento" value="21" /> <!-- código 21 para emitir segunda via de boleto já registrado -->`
            `<input type="hidden" name="cpfCnpj" value="00000000000" />`
            `<input type="hidden" name="indicadorPessoa" value="1" />`
            `<input type="hidden" name="valorDesconto" value="0" />`
            `<input type="hidden" name="dataLimiteDesconto" value="10012019" />`
            `<input type="hidden" name="tpDuplicata" value="DS" />`
            `<input type="hidden" name="urlRetorno" value="http://boleto.agn.rn.gov.br/Pagamento.aspx" />`
            `<input type="hidden" name="urlInforma" value="" />`
            `<input type="hidden" name="nome" value="NOME DO CLIENTE" />`
            `<input type="hidden" name="endereco" value="ENDERECO DO CLIENTE" />`
            `<input type="hidden" name="cidade" value="CARAUBAS" />`
            `<input type="hidden" name="uf" value="RN" />`
            `<input type="hidden" name="cep" value="59780000" />`
            `<input type="hidden" name="msgLoja" value="Nao receber apos a data de vencimento" />`
            `<input class="btn btn-primary" type="submit" value="Imprimir"/>`
        `</form>`


Alguém tem alguma ideia do que está errado?
