### ISSUE TITLE
Formatação dos campos

### ISSUE THREAD

**Issue by rafaelpatro** [rafaelpatro/Quack-BB#5]
Formatar os campos _nome, endereço, etc_, de acordo com o manual, antes de encaminhar ao banco.
![image](https://cloud.githubusercontent.com/assets/13813964/21981991/4f9b5f0c-dbd1-11e6-94a3-ca7bceade20b.png)

**Comment by mageuser** [comment]
Olá, os campos não estão sendo tratados? Será necessário que eu formate para esse padrão ou o módulo já dispõe essa funcionalidade?

Obrigado, gostaria também, se possível, que o senhor ajude-me com esse problema:
https://github.com/rafaelpatro/Quack_BB/issues/6

Atenciosamente, Kauan.

**Comment by rafaelpatro** [comment]
Olá @kauanguesser 
Essa formatação que mencionei não é um requisito. É apenas para prevenir algumas possibilidades de erros.
O Banco do Brasil atualizou a documentação há algum tempo, e ainda não tive tempo de atualizar esta extensão.
Atualmente esta extensão funciona na modalidade de Débito em Conta apenas.
