### ISSUE TITLE
OSC Magento Brasil 6 Pro - Não exibe método de pagamento

### ISSUE THREAD

**Issue by mageuser** [rafaelpatro/Quack-BB#6]
A opção de pagamento - Banco do brasil (bankline) não aparece na lista para ser selecionado como forma de pagamento.
Você poderia ajudar? Estarei doando para ajudar a manter o módulo ativo.

Obrigado.

Link do módulo:
https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro

**Comment by rafaelpatro** [comment]
Olá @kauanguesser 
Recomendo fazer o checklist a seguir.
1. Verifique se vc já escolheu a forma de entrega na Finalização do Pedido.
2. Verifique se o módulo está ativo em Formas de Pagamento, nas configurações do Magento.
3. Verifique se há valor mínimo configurado nas configurações do módulo.

**Comment by mageuser** [comment]
Amigo deu certo, também selecionei o País, estava para todos, após isso salvei e selecionei a opção Para todos os países e deu certo. Agora estou com dúvidas sobre:  URL Informa,  URL Retorno, coloquei em ambos /sales/order/history/ conforme a página do github, e ao selecionar boleto bancário o bb informou que o cnpj não é conveniado a este serviço, e cliquei em voltar, gerou erro 404 nesta url: https://mpag.bb.com.br/sales/order/history/

Obrigado pela ajuda!

Atenciosamente, Kauan.

**Comment by mageuser** [comment]
Após ser redirecionado para a página do mpag, aparece Loja Conveniada : 	TESTE- HORTIBRAS, gostaria de saber se esse TESTE está vindo do módulo.


Atenciosamente, Kauan.

**Comment by rafaelpatro** [comment]
Não. Este TESTE é do banco

**Comment by mageuser** [comment]
A Opção por boleto bancário não funciona, mensagem do banco:

 	

Atenção!

Os dados enviados pela loja apresentaram os seguintes problemas:

    CPF/CNPJ não informado para cobrança registrada (C031-000)


O senhor poderia me ajudar?

**Comment by mageuser** [comment]
Certo, então tem que passar por um processo de validação.

**Comment by mageuser** [comment]
Em relação ao URL retorno eu entendi, fique com dúvidas somente no URL informa

**Comment by rafaelpatro** [comment]
Já lhe encaminho um print das configurações

**Comment by rafaelpatro** [comment]
Segue exemplo de configuração:
![image](https://cloud.githubusercontent.com/assets/13813964/24963819/13b5bff8-1f76-11e7-8571-1b88ef45a124.png)
![image](https://cloud.githubusercontent.com/assets/13813964/24963887/39d00fe0-1f76-11e7-9cdb-c69be675aa6d.png)

**Comment by rafaelpatro** [comment]
Como mencionei no outro tópico #5, o Banco do Brasil atualizou a documentação, e ainda não tive tempo de ajustar o módulo. O boleto não está funcionando mesmo.

**Comment by mageuser** [comment]
Obrigado, pelas respostas, como posso proceder para fazer o boleto funcionar? São correções simples?

**Comment by rafaelpatro** [comment]
Sim, é bem simples. Basta seguir o [manual do banco](http://www.bb.com.br/docs/pub/emp/empl/dwn/Orientacoes.pdf)

Assim que der uma brecha, eu trabalharei nisso.
Se quiser contribuir com estes ajustes, sinta-se a vontade para enviar uma PR.

**Comment by mageuser** [comment]
O senhor gostaria de fazer estes ajustes? Nós podemos combinar um valor para realizar como doação.
Tenho dúvidas de como proceder, eu programo em php, porem estou familiarizando com o Magento. Eu posso estar fazendo essas alterações só preciso de uma luz, em quais arquivos devem ser feitos, variáveis, etc.

**Comment by rafaelpatro** [comment]
@kauanguesser 
Acho que consigo implementar estes ajustes antes do final-de-semana.

Caso queira contribuir, doando qualquer valor, sinta-se à vontade; ficarei grato, e dedicarei mais tempo neste projeto. Mas por favor não doe esperando retorno. Para isso há opções pagas disponíveis, como o [Cerebrum](https://www.cerebrum.com.br/modulo-banco-brasil-magento/).

**Comment by mageuser** [comment]
Rafael, obrigado pelas respostas, espero esse final de semana, posso ficar a sua disposição para estar lhe ajudando. Quanto a doação, não espero em forma de retorno, penso que é uma motivação.

Obrigado!

**Comment by rafaelpatro** [comment]
@kauanguesser pode testar esse branch, e ver se o boleto funciona?
https://github.com/rafaelpatro/Quack_BB/tree/doc-update-v23.3

**Comment by mageuser** [comment]
@rafaelpatro obrigado pela atenção! Posso sim, só vou poder dar o retorno mais tarde ok? Só consigo doar 1 ou 5 reais? Não é possível digitar a quantia que eu quiser?

**Comment by rafaelpatro** [comment]
Sim, estou adicionando um link para doações mais generosas.
Pode usar este aqui: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=G96XYMZU65MYS
