### ISSUE TITLE
There has been an error processing your request

### ISSUE THREAD

**Issue by mageuser** [rafaelpatro/Quack-BB#9]
Após finalizar a compra no checkout, o módulo retornou erro na url:
bb/standard/redirect/

Magento 1.9.3.2

a:5:{i:0;s:75:"Não foi possível recuperar informações de pagamento do instance object.";i:1;s:1623:"#0 /home/wwwhortibrascom/public_html/app/code/core/Mage/Payment/Model/Method/Abstract.php(380): Mage::throwException('N\xC3\xA3o foi poss\xC3\xAD...')
#1 /home/wwwhortibrascom/public_html/app/code/community/Quack/BB/Model/Standard.php(127): Mage_Payment_Model_Method_Abstract->getInfoInstance()
#2 /home/wwwhortibrascom/public_html/app/code/community/Quack/BB/Model/Standard.php(158): Quack_BB_Model_Standard->getTpPagamento()
#3 /home/wwwhortibrascom/public_html/app/code/community/Quack/BB/Block/Redirect.php(49): Quack_BB_Model_Standard->getRedirectFields()
#4 /home/wwwhortibrascom/public_html/app/code/core/Mage/Core/Block/Abstract.php(922): Quack_BB_Block_Redirect->_beforeToHtml()
#5 /home/wwwhortibrascom/public_html/app/code/community/Quack/BB/controllers/StandardController.php(75): Mage_Core_Block_Abstract->toHtml()
#6 /home/wwwhortibrascom/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Quack_BB_StandardController->redirectAction()
#7 /home/wwwhortibrascom/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('redirect')
#8 /home/wwwhortibrascom/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 /home/wwwhortibrascom/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#10 /home/wwwhortibrascom/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#11 /home/wwwhortibrascom/public_html/index.php(83): Mage::run('', 'store')
#12 {main}";s:3:"url";s:22:"/bb/standard/redirect/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}

**Comment by rafaelpatro** [comment]
Perae...

**Comment by mageuser** [comment]
Posso testar, ou devo esperar caso exista alguma pendência...?

**Comment by rafaelpatro** [comment]
Pode testar!
Vou dar um 👍 no seu comentário, sempre que estiver liberado pra teste, ok?!

**Comment by mageuser** [comment]
@rafaelpatro Certo, muitíssimo obrigado!
